name: first-try
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout different repository
      uses: actions/checkout@v2
      with:
        repository: rahul-aws/hello-world
        ref: main
